In [28]:
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt

# New Section

In [2]:
Df = pd.read_csv('Tweets.csv')

In [3]:
Df

tweet_id airline_sentiment  airline_sentiment_confidence  \
0      570306133677760513           neutral                        1.0000   
1      570301130888122368          positive                        0.3486   
2      570301083672813571           neutral                        0.6837   
3      570301031407624196          negative                        1.0000   
4      570300817074462722          negative                        1.0000   
...                   ...               ...                           ...   
14635  569587686496825344          positive                        0.3487   
14636  569587371693355008          negative                        1.0000   
14637  569587242672398336           neutral                        1.0000   
14638  569587188687634433          negative                        1.0000   
14639  569587140490866689           neutral                        0.6771   

               negativereason  negativereason_confidence         airline  \
0                         NaN                        NaN  Virgin America   
1                         NaN                     0.0000  Virgin America   
2                         NaN                        NaN  Virgin America   
3                  Bad Flight                     0.7033  Virgin America   
4                  Can't Tell                     1.0000  Virgin America   
...                       ...                        ...             ...   
14635                     NaN                     0.0000        American   
14636  Customer Service Issue                     1.0000        American   
14637                     NaN                        NaN        American   
14638  Customer Service Issue                     0.6659        American   
14639                     NaN                     0.0000        American   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN          cairdin                 NaN   
1                        NaN         jnardino                 NaN   
2                        NaN       yvonnalynn                 NaN   
3                        NaN         jnardino                 NaN   
4                        NaN         jnardino                 NaN   
...                      ...              ...                 ...   
14635                    NaN  KristenReenders                 NaN   
14636                    NaN         itsropes                 NaN   
14637                    NaN         sanyabun                 NaN   
14638                    NaN       SraJackson                 NaN   
14639                    NaN        daviddtwu                 NaN   

       retweet_count                                               text  \
0                  0                @VirginAmerica What @dhepburn said.   
1                  0  @VirginAmerica plus you've added commercials t...   
2                  0  @VirginAmerica I didn't today... Must mean I n...   
3                  0  @VirginAmerica it's really aggressive to blast...   
4                  0  @VirginAmerica and it's a really big bad thing...   
...              ...                                                ...   
14635              0  @AmericanAir thank you we got on a different f...   
14636              0  @AmericanAir leaving over 20 minutes Late Flig...   
14637              0  @AmericanAir Please bring American Airlines to...   
14638              0  @AmericanAir you have my money, you change my ...   
14639              0  @AmericanAir we have 8 ppl so we need 2 know h...   

      tweet_coord              tweet_created tweet_location  \
0             NaN  2015-02-24 11:35:52 -0800            NaN   
1             NaN  2015-02-24 11:15:59 -0800            NaN   
2             NaN  2015-02-24 11:15:48 -0800      Lets Play   
3             NaN  2015-02-24 11:15:36 -0800            NaN   
4             NaN  2015-02-24 11:14:45 -0800            NaN   
...           ...                        ...            ...   
14635   

In [4]:
print(Df.describe())

           tweet_id  airline_sentiment_confidence  negativereason_confidence  \
count  1.464000e+04                  14640.000000               10522.000000   
mean   5.692184e+17                      0.900169                   0.638298   
std    7.791112e+14                      0.162830                   0.330440   
min    5.675883e+17                      0.335000                   0.000000   
25%    5.685592e+17                      0.692300                   0.360600   
50%    5.694779e+17                      1.000000                   0.670600   
75%    5.698905e+17                      1.000000                   1.000000   
max    5.703106e+17                      1.000000                   1.000000   

       retweet_count  
count   14640.000000  
mean        0.082650  
std         0.745778  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max        44.000000  


# Prepreocessing


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df.isna().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [5]:
x = Df.iloc[:,:-1].values
y = Df.iloc[:,-1].values
print(x)

[[570306133677760513 'neutral' 1.0 ... nan '2015-02-24 11:35:52 -0800'
  nan]
 [570301130888122368 'positive' 0.3486 ... nan
  '2015-02-24 11:15:59 -0800' nan]
 [570301083672813571 'neutral' 0.6837 ... nan '2015-02-24 11:15:48 -0800'
  'Lets Play']
 ...
 [569587242672398336 'neutral' 1.0 ... nan '2015-02-22 11:59:15 -0800'
  'Nigeria,lagos']
 [569587188687634433 'negative' 1.0 ... nan '2015-02-22 11:59:02 -0800'
  'New Jersey']
 [569587140490866689 'neutral' 0.6771 ... nan '2015-02-22 11:58:51 -0800'
  'dallas, TX']]


# Feature Engineering

In [20]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filtered_data = data[data > 5]

sorted_data = np.sort(filtered_data)[::-1]

print(sorted_data)




[10  9  8  7  6]


# Model Training

In [42]:
# Import Python libraries for data manipuation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyplot

# Import the Python machine learning libraries we need
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [45]:
# Split into test and training sets
test_size = 0.33
seed = 7
x_train, x_test, y_train, y_test =  train_test_split(x, y, test_size=test_size, random_state=seed)

In [46]:
x_train

array([3.21611601, 3.1127265 , 4.73118467, 3.50185721, 2.84356583,
       0.56523242, 2.34674973, 2.96042976, 0.65639681, 3.06648901,
       1.14138761, 3.77101174, 3.55145404, 0.34055054, 4.04082395,
       1.57878277, 2.81053074, 2.8465048 , 5.23136679, 2.9808695 ,
       2.92278133, 2.94373317, 2.59610773, 2.90854738, 4.21788563,
       4.64027081, 4.35963386, 3.38186623, 2.09099239, 3.61134078,
       1.20656441, 3.00000976, 3.35088849, 3.37044454, 0.95967695,
       2.8676711 , 2.92552924, 0.96653345, 2.66117803, 2.36532069,
       3.73527958, 3.32600343, 3.82470301, 2.58068352, 3.00902525,
       3.50288142, 4.27837923, 4.58448706, 2.58324215, 4.46767801,
       1.75471191, 2.17086471, 4.1735315 , 3.54235257, 1.94204778,
       1.13190935, 2.61848352, 1.2620405 , 3.53905832, 3.50839624,
       3.20420798, 2.01122095, 4.24821292, 1.56056097, 2.76381597,
       3.52429643, 3.04797059])

In [47]:
y_train

array([ 68.30365792,  55.79245737,  14.09666443,  25.90093643,
        58.83311239, 190.30762228,  90.02681869,  44.34023444,
       208.47130994,  59.01318439, 115.73628743,  37.10649687,
        38.57519009, 487.03726791,  54.98360439, 123.11113005,
        72.37873053,  27.89501382,  24.86406278,  40.94657678,
        55.46264153,  56.20180641,  70.55883508,  47.24533754,
        32.35727584,  36.05903817,  43.76381026,  55.71813453,
        60.57574247,  61.39097018, 114.23885932,  56.63901768,
        52.19177448,  42.32964984, 161.50533328,  65.39332448,
        22.97550427, 202.76589695,  68.37843898,  82.32095959,
        48.95077634,  30.00934597,  34.46826737,  38.66530343,
        30.26663537,  63.77986643,  39.01941998,  25.07604874,
        76.05204933,  62.93869329,  95.52998052,  81.92492065,
        45.84155234,  43.77321677,  62.4237197 ,  77.86225629,
        62.86162946,  80.14230427,  39.26265343,  39.62788318,
        32.65308038,  83.01076429,  40.15213735, 108.86

In [48]:
x_test

array([2.1557863 , 2.36234499, 3.69511961, 3.56627544, 3.08771022,
       2.4038403 , 4.40669624, 3.84245628, 4.36723542, 3.25657045,
       1.88207455, 2.6864918 , 2.62433058, 3.04153939, 2.53799465,
       2.66432266, 5.29220801, 2.32232442, 2.12189211, 2.25212905,
       4.00036589, 0.8638039 , 4.17500122, 1.61548133, 2.15825263,
       2.78286473, 2.61890748, 2.73094304, 1.90126105, 3.38047197,
       3.04625552, 3.43349633, 1.81238771])

In [49]:
y_test

array([ 85.28325651,  76.22874513,  34.16662793,  50.5667094 ,
        57.61442568,  53.79918302,  27.61777936,  18.36485932,
        21.035144  ,  42.08623741,  67.13926856,  34.70979433,
        53.67848811,  37.45148182,  64.76189111,  70.87521926,
        24.10914678,  68.74904453,  51.4368334 , 111.90190427,
        43.5111781 , 121.17874037,  27.02857247, 108.46604975,
       117.41526024,  61.85229524,  57.3316853 ,  53.25015791,
        71.22685026,  46.50723143,  59.1743156 ,  50.79538368,
        60.83111238])

# Employing NLP techniques Generating insights

In [72]:
import nltk
from nltk.tokenize import word_tokenize
import spacy

nltk.download('punkt')
nlp = spacy.load('en_core_web_sm')

text = "Natural Language Processing is fascinating!"
tokens_nltk = word_tokenize(text)
tokens_spacy = [token.text for token in nlp(text)]

print("NLTK tokens:", tokens_nltk)
print("spaCy tokens:", tokens_spacy)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


NLTK tokens: ['Natural', 'Language', 'Processing', 'is', 'fascinating', '!']
spaCy tokens: ['Natural', 'Language', 'Processing', 'is', 'fascinating', '!']


In [73]:
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

filtered_tokens = [token for token in tokens_nltk if token.lower() not in stop_words]

print("Filtered tokens:", filtered_tokens)

Filtered tokens: ['Natural', 'Language', 'Processing', 'fascinating', '!']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [74]:
doc = nlp(text)
pos_tags = [(token.text, token.pos_) for token in doc]

print("POS tags:", pos_tags)

POS tags: [('Natural', 'PROPN'), ('Language', 'PROPN'), ('Processing', 'PROPN'), ('is', 'AUX'), ('fascinating', 'ADJ'), ('!', 'PUNCT')]


In [75]:
entities = [(ent.text, ent.label_) for ent in doc.ents]

print("Named Entities:", entities)

Named Entities: []
